export default{
	baseUrl : 'http://127.0.0.1:12306',
	getAreaByOverSea : '/api/getAreaByOverSea',
	getProvinceByArea : '/api/getProvinceByArea',
	getCityByProvince : '/api/getCityByProvince',
	getHotCitys : '/api/getHotCitys',
	getPicByPath : '/api/getPicByPath',
	getHotAreas : '/api/getHotAreas',
	registUser : '/api/userRegist',
	signIn : '/api/userSignIn',
	getUserInfo : '/api/user/getUserInfo',
	signOut : '/api/user/signOut',
	getAllAreaByPage : '/api/getAllAreaByPage',
	getAreaByAreaId : '/api/getAreaByAreaId',
	getProvinceByAreaIdPage : '/api/getProvinceByAreaIdPage',
	getCityPageByProvince : '/api/getCityPageByProvince',
	getAreaByProvinceId : '/api/getAreaByProvinceId',
	getPaysageListPageByCityId : '/api/getPaysageListPageByCityId',
	getCityByCityId  : '/api/queryCityByCityId' ,
	getPaySageProfieByPaysageId : '/api/getPaySageProfieByPaysageId',
	getPaysageImgPageByPaysageId : '/api/getPaysageImgPageByPaysageId',
	getCommentPageByPaysageId : '/api/getCommentPageByPaysageId',
	getUserComment : '/api/getUserComment',
	updateUseread : '/api/updateUseread',
	deleteCommentByCommentId : '/api/deleteCommentByCommentId',
	updateUserInfoById : '/api/updateUserInfoById',
	getUserInfoById : '/api/getUserInfoById',
	updatePassword : '/api/updatePassword',
	submitComment : '/api/submitComment',
	searchByWord  : '/api/searchByWord'
}
